version: '3.9'

services:
  app:
    image: ${DOCKERHUB_USERNAME}/${PROJECT_NAME}:latest # docker image 이름
    container_name: spring_boot_app
    ports:
      - "8080:8080" # application port
    networks:
      - app-network
    restart: always # 컨테이너가 중지되면 항상 재시작
    environment:
      LOGSTASH_HOST: logstash # Logstash 서비스 이름
      SPRING_DATASOURCE_URL: jdbc:mysql://host.docker.internal:3306/${{ secrets.MYSQL_DBNAME }}?serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: ${{ secrets.MYSQL_USERNAME }}
      SPRING_DATASOURCE_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}

  elasticsearch:
    build:
      context: ./elk/elasticsearch
      dockerfile: Dockerfile
    container_name: elasticsearch
    ports:
      - "9200:9200"
    networks:
      - app-network

  logstash:
    build:
      context: ./elk/logstash
      dockerfile: Dockerfile
    container_name: logstash
    ports:
      - "5044:5044"
    networks:
      - app-network

  kibana:
    build:
      context: ./elk/kibana
      dockerfile: Dockerfile
    container_name: kibana
    ports:
      - "5601:5601"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge