scrape_configs:
  - job_name: 'furniture'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 10s
    static_configs:
      - targets: ['furniture:8080']
  - job_name: 'health-check'
    metrics_path: '/actuator/health'
    static_configs:
      - targets: ['furniture:8080']